### ISSUE TITLE
RoadMap

### ISSUE THREAD

**Issue by rhenandias** [Biblioteca-de-Bolso/backend#51]
### Legenda:
⚠️  Ainda não possui testes automatizados
✔️  Possui testes automatizados

### Usuário

- [x] Criar usuário ✔️
- [x] Ler usuário ✔️ 
- [x] Alterar senha ✔️
- [x] Solicitar alteração/recuperação de senha ✔️ 
- [x] Remover usuário ✔️ 

### Livros

- [x] Criar livro ✔️
- [x] Ler livro ✔️
- [x] Listar livros ✔️
- - [x] Mecanismos de busca nos próprios livros ✔️
- - [x] Listar livros por status de leitura ⚠️ 
- [x] Atualizar livro parcialmente (patch) ⚠️ 
- [x] Atualizar livro por completo (put) ⚠️ 
- [x] Remover livro ✔️
- [x] Atualizar foto de capa ⚠️ 
- [x] Remover foto de capa ⚠️ 

### Anotações

- [x]  Criar anotação ✔️
- [x] Ler anotação ✔️ 
- [x] Atualizar anotação (put) ⚠️ 
- [x] Remover anotação ⚠️ 
- [x] Listar anotações ✔️  
- - [x] Mecanismos de busca nas anotações ⚠️ 
- [x] Exportar anotação para PDF ⚠️ 

### Empréstimos

- [x] Criar empréstimo ⚠️ 
- [x] Editar empréstimo parcialmente (patch) ⚠️ 
- [x] Listar empréstimos ⚠️  
- - [x] Mecanismo de busca nos empréstimos ⚠️  
- - [x] Filtrar emprésitmos por livro ⚠️  
- [x] Remover empréstimo ⚠️ 
- [x] Ler os dados de um empréstimo específico ⚠️
